import { readdir, rm, stat } from 'node:fs/promises';
import path from 'node:path';

/* `tmp/` holds two unrelated things: output the tooling can regenerate, and
   review checklists, scratch notes and validation artifacts that AGENTS.md
   asks contributors to keep there. So this removes an allowlist rather than
   emptying the directory: anything not named below is reported and left alone.
   Every entry is a path some script, config or test actually writes — keep it
   that way, and check the writer still exists before adding one. */

// Regenerated by a build, a test run or a report command.
const generated = [
  'site',                    // scripts/build.mjs
  'test-results',            // playwright.config.mjs outputDir
  'playwright-report',       // playwright.config.mjs html reporter
  'slides-preview-site',     // hugo.slides-preview.toml publishDir
  'slides-preview-build',    // tools/slides/preview-test-server.mjs
  'slides-preview-tests',    // tools/slides/preview.config.mjs outputDir
  'slides-render',           // tools/slides/render.mjs staging
  'prose-pilot',             // scripts/test-prose.mjs
  'prose-report.json',       // scripts/prose.mjs
  'external-report.json',    // scripts/external.mjs
  /^slides-editor-test-/,    // tools/slides/editor.test.mjs mkdtemp
  /^(rendering|hugo|path|check|assignment)-fixture-/,  // tests/unit mkdtemp
  /^(tree-guide|parser-layout|annotated-alphabet)-.*\.png$/  // pre-outputPath spec screenshots
];

// Downloaded or installed once and reused; removing these costs a re-download.
const caches = [
  'playwright-browsers',     // scripts/playwright.mjs
  'bin',                     // scripts/install-vale.mjs
  'vale.tar.gz',             // scripts/install-vale.mjs
  'npm-cache',
  'excalidraw-tools',        // docs/technical/caveats.md
  'notation-font-tools',     // scripts/build-notation-font.py
  'slides-runtime'           // tools/slides/runtime.mjs bundle and work dirs
];

const matches = (name, rules) => rules.some(r => typeof r === 'string' ? r === name : r.test(name));

async function sizeOf(target) {
  const info = await stat(target);
  if (!info.isDirectory()) return info.size;
  const entries = await readdir(target, { withFileTypes: true });
  return (await Promise.all(entries.map(e => sizeOf(path.join(target, e.name))))).reduce((a, b) => a + b, 0);
}

const mb = bytes => `${(bytes / 1e6).toFixed(1)} MB`;

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const withCaches = args.includes('--caches') || args.includes('--all');
const rules = withCaches ? [...generated, ...caches] : generated;

const root = 'tmp';
let entries;
try { entries = await readdir(root); }
catch { console.log('Nothing to clean: tmp/ does not exist.'); process.exit(0); }

const doomed = entries.filter(name => matches(name, rules));
// slides-runtime holds a reusable bundle alongside per-run work dirs, so its
// work dirs go with the generated group and the bundle only with --caches.
const runtimeWork = [];
if (!withCaches && entries.includes('slides-runtime')) {
  for (const name of await readdir(path.join(root, 'slides-runtime'))) {
    if (/^(editor|export)-/.test(name)) runtimeWork.push(path.join('slides-runtime', name));
  }
}

const targets = [...doomed, ...runtimeWork];
if (!targets.length) {
  console.log(`Clean: nothing to remove${withCaches ? '' : ' (use --caches to include downloaded tools)'}.`);
} else {
  let freed = 0;
  for (const name of targets) {
    const target = path.join(root, name);
    const size = await sizeOf(target).catch(() => 0);
    freed += size;
    if (!dryRun) await rm(target, { recursive: true, force: true });
    console.log(`${dryRun ? 'would remove' : 'removed'} ${target} (${mb(size)})`);
  }
  console.log(`Clean: ${dryRun ? 'would free' : 'freed'} ${mb(freed)} across ${targets.length} entries.`);
}

const kept = entries.filter(name => !matches(name, rules));
if (kept.length) {
  console.log(`Kept ${kept.length} other entries in tmp/ (review notes and scratch files are never removed).`);
  if (!withCaches) {
    const cached = kept.filter(name => matches(name, caches));
    if (cached.length) console.log(`  ${cached.length} of them are downloaded tools; --caches removes those too.`);
  }
}
