#!/usr/bin/env python3
"""
Bootstrap Icons subset
======================

The site uses about two dozen icons. The upstream font ships ~2,000, which costs
130KB of woff2 and 84KB of CSS on every page. This keeps only what is used, so
every existing `<i class="bi bi-…">` keeps working untouched.

    hugo -D -d tmp/site            # so the used icons can be read off the site
    python3 scripts/subset-icons.py

Writes assets/icons/subset/bootstrap-icons-subset.{woff2,css}.
A test (tests/browser/icons.spec.mjs) fails if a page uses an icon the subset
does not carry, so adding one cannot silently break.

Needs: pip install fonttools brotli
"""
import os, re, sys, glob
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS_IN = os.path.join(ROOT, 'assets/icons/font/bootstrap-icons.css')
WOFF2_IN = os.path.join(ROOT, 'assets/icons/font/fonts/bootstrap-icons.woff2')
OUT_DIR = os.path.join(ROOT, 'assets/icons/subset')
SITE = os.path.join(ROOT, 'tmp/site')

# Icons that only ever appear at runtime. Scanning HTML alone misses these:
# dropping bi-sun and bi-moon-stars made the theme toggle render an empty box
# the moment it was clicked.
EXTRA = {'bi-x-lg', 'bi-check-lg'}

def used_icons():
    names = set()
    sources = (glob.glob(f'{SITE}/**/*.html', recursive=True)
               + glob.glob(f'{ROOT}/layouts/**/*.html', recursive=True)
               + glob.glob(f'{ROOT}/content/**/*.md', recursive=True)
               + glob.glob(f'{ROOT}/assets/js/*.js')
               + glob.glob(f'{ROOT}/assets/css/*.css'))
    for src in sources:
        if '/assets/bootstrap/' in src or '/assets/icons/' in src:
            continue
        try:
            text = open(src, errors='ignore').read()
        except OSError:
            continue
        # only inside a class attribute, so filenames like bi-conditional.png
        # are not mistaken for icon classes
        for attr in re.findall(r'class="([^"]*)"', text):
            names |= {c for c in attr.split() if c.startswith('bi-')}
        names |= set(re.findall(r'\bbi\s+(bi-[a-z0-9-]+)', text))
        # scripts swap icon classes in and out, and CSS may select them
        if src.endswith(('.js', '.css')):
            names |= set(re.findall(r'["\'.]\s*(bi-[a-z0-9-]+)', text))
    return {n for n in names if n not in ('bi-', 'bi-icons')} | EXTRA

def main():
    if not os.path.exists(SITE):
        sys.exit('Build the site first: hugo -D -d tmp/site')
    if not os.path.exists(CSS_IN):
        sys.exit(f'missing {CSS_IN}')
    css = open(CSS_IN).read()
    # .bi-name::before { content: "\f123"; }
    rules = dict(re.findall(r'\.(bi-[a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', css))
    wanted = used_icons()
    keep = {n: cp for n, cp in rules.items() if n in wanted}
    missing = sorted(wanted - set(rules) - EXTRA)

    os.makedirs(OUT_DIR, exist_ok=True)
    codepoints = {int(cp, 16) for cp in keep.values()}

    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.desubroutinize = True
    opts.layout_features = []
    opts.name_IDs = ['*']
    font = subset.load_font(WOFF2_IN, opts)
    subsetter = subset.Subsetter(options=opts)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    out_font = os.path.join(OUT_DIR, 'bootstrap-icons-subset.woff2')
    subset.save_font(font, out_font, opts)

    lines = ['/* Generated by scripts/subset-icons.py — do not edit.',
             f' * {len(keep)} of the ~2,000 Bootstrap Icons, the ones this site actually uses.',
             ' */',
             '@font-face {',
             '  font-family: "bootstrap-icons";',
             '  font-display: block;',
             '  src: url("/icons/subset/bootstrap-icons-subset.woff2") format("woff2");',
             '}',
             '.bi::before, [class^="bi-"]::before, [class*=" bi-"]::before {',
             '  display: inline-block;',
             '  font-family: bootstrap-icons !important;',
             '  font-style: normal; font-weight: normal !important;',
             '  font-variant: normal; text-transform: none;',
             '  line-height: 1; vertical-align: -.125em;',
             '  -webkit-font-smoothing: antialiased;',
             '}']
    for name in sorted(keep):
        lines.append(f'.{name}::before {{ content: "\\{keep[name]}"; }}')
    out_css = os.path.join(OUT_DIR, 'bootstrap-icons-subset.css')
    open(out_css, 'w').write('\n'.join(lines) + '\n')

    before = os.path.getsize(WOFF2_IN) + os.path.getsize(CSS_IN)
    after = os.path.getsize(out_font) + os.path.getsize(out_css)
    print(f'kept {len(keep)} icons: {sorted(keep)}')
    if missing:
        print(f'WARNING: used but not in the icon set: {missing}')
    print(f'{before/1024:.0f}KB -> {after/1024:.0f}KB '
          f'(font {os.path.getsize(out_font)/1024:.1f}KB, css {os.path.getsize(out_css)/1024:.1f}KB)')

main()
