import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { proseText } from './prose-text.mjs';
await mkdir('tmp/prose-pilot', { recursive: true });
const source = await readFile('tests/vale-pilot.md', 'utf8');
await writeFile('tmp/prose-pilot/english.md', proseText(source));
await mkdir('tmp/prose-pilot/verdiepingspakketten', { recursive: true });
await writeFile('tmp/prose-pilot/verdiepingspakketten/dutch.md', 'Dit is een een mispelingdutch.');
const result = spawnSync(process.env.VALE_BIN || 'vale', ['--config=.vale.ini', '--no-exit', '--output=JSON', 'tmp/prose-pilot'], { encoding: 'utf8' });
assert.equal(result.status, 0, result.error?.message || result.stderr || result.stdout);
const report = JSON.parse(result.stdout);
const english = Object.entries(report).find(([key]) => key.endsWith('english.md'))?.[1] || [];
const dutch = Object.entries(report).find(([key]) => key.endsWith('dutch.md'))?.[1] || [];
assert(english.some(f => f.Check === 'LogicalMethods.Repetition'));
assert(english.some(f => f.Match === 'mispelingvisible'));
assert(english.some(f => f.Match === 'mispelinginner'));
// Recognize course vocabulary without hiding misspellings or emphasis text.
const misspellings = english.filter(f => f.Check === 'Vale.Spelling').map(f => f.Match).sort();
assert.deepEqual(misspellings, ['Programe', 'countermodle', 'mispelingemphasis', 'mispelinginner', 'mispelingvisible'].sort());
assert(!english.some(f => /mispeling(?:Hidden|attribute|formula|code|percent|block)/i.test(f.Match)));
assert(dutch.some(f => f.Check === 'LogicalMethods.Repetition'));
assert(!dutch.some(f => f.Check === 'Vale.Spelling'));
console.log('Vale pilot: prose and repetition detected, notation excluded, Dutch language override applied.');
