import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { slideEntries, orderedFrames } from './model.mjs';
import { root } from './runtime.mjs';
import { chromium } from 'playwright';

test('local editor edits, saves, backs up, rejects conflicts and retains original data', { timeout: 90000 }, async () => {
  const fixture = await fs.mkdtemp(path.join(root, 'tmp/slides-editor-test-'));
  await fs.cp(path.join(root, 'slides/sources'), path.join(fixture, 'sources'), { recursive: true });
  const firstManifest = JSON.parse(await fs.readFile(path.join(root, 'slides/lecture-1.json')));
  await fs.copyFile(path.join(root, 'slides/lecture-1.json'), path.join(fixture, 'lecture-1.json'));
  await fs.copyFile(path.join(root, 'slides/sources/Lecture 1.excalidraw'), path.join(fixture, 'sources/Lecture 2.excalidraw'));
  await fs.writeFile(path.join(fixture, 'lecture-2.json'), JSON.stringify({ ...firstManifest, id: 'lecture-2', title: 'Lecture 2: Editor fixture', source: 'sources/Lecture 2.excalidraw' }));
  const initialCount = firstManifest.slides.length;
  await fs.copyFile(path.join(root, 'slides/library.excalidrawlib'), path.join(fixture, 'library.excalidrawlib'));
  const child = spawn(process.execPath, ['tools/slides/editor-server.mjs'], { cwd: root, env: { ...process.env, SLIDES_PORT: '4184', SLIDES_DATA_DIR: fixture }, stdio: ['ignore', 'pipe', 'pipe'] });
  let browser; let output = '';
  child.stderr.on('data', d => { output += d; });
  try {
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(Error(`Editor did not start: ${output}`)), 20000);
      child.stdout.on('data', d => { output += d; if (output.includes('Local Excalidraw editor:')) { clearTimeout(timer); resolve(); } });
      child.once('exit', code => { clearTimeout(timer); reject(Error(`Editor exited ${code}: ${output}`)); });
    });
    browser = await chromium.launch();
    const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
    const failures = [];
    page.on('pageerror', e => failures.push(e.message));
    page.on('console', m => { if (m.type() === 'error') failures.push(m.text()); });
    page.on('request', r => { if (new URL(r.url()).protocol.startsWith('http') && new URL(r.url()).hostname !== '127.0.0.1') failures.push(r.url()); });
    await page.goto('http://127.0.0.1:4184');
    await page.locator('.excalidraw canvas').first().waitFor();
    // A library API failure must not leave an empty editor shell.
    await page.route('**/api/library', route => route.fulfill({ json: { error: 'Library unavailable in regression fixture' } }));
    await page.reload();
    await page.getByRole('alert').filter({ hasText: 'Icon library could not load' }).waitFor();
    await page.locator('.excalidraw canvas').first().waitFor();
    assert.equal(await page.getByRole('button', { name: 'Save library', exact: true }).isDisabled(), true);
    await page.unroute('**/api/library');
    await page.reload();
    await page.locator('.excalidraw canvas').first().waitFor();
    await page.getByLabel('Choose lecture').click();
    await page.getByRole('button', { name: 'Lecture 2: Editor fixture', exact: true }).click();
    await page.getByRole('button', { name: 'Save source', exact: true }).waitFor();
    await page.waitForFunction(() => !document.querySelector('.local-editor__bar button').disabled);
    const originalRaw = await fs.readFile(path.join(fixture, 'sources/Lecture 2.excalidraw'), 'utf8');
    const original = JSON.parse(originalRaw);
    await page.waitForTimeout(600);
    await page.locator('label').filter({ has: page.locator('[data-testid="toolbar-text"]') }).click();
    await page.mouse.click(800, 500);
    const text = page.locator('textarea.excalidraw-wysiwyg');
    await text.waitFor(); await text.fill('Editor regression fixture');
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Save source', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Saved. A backup was kept.' }).waitFor();
    const saved = JSON.parse(await fs.readFile(path.join(fixture, 'sources/Lecture 2.excalidraw'), 'utf8'));
    assert.ok(saved.elements.some(e => e.text === 'Editor regression fixture'));
    assert.deepEqual(saved.metadata, original.metadata);
    for (const [id, file] of Object.entries(original.files)) assert.deepEqual(saved.files[id], file);
    for (const element of original.elements) assert.ok(saved.elements.some(e => e.id === element.id));
    const backups = await fs.readdir(path.join(root, 'tmp/slides-backups/lecture-2'));
    const latest = backups.sort().at(-1);
    assert.equal(await fs.readFile(path.join(root, 'tmp/slides-backups/lecture-2', latest), 'utf8'), originalRaw);
    const conflict = await page.request.put('http://127.0.0.1:4184/api/decks/lecture-2', { headers: { Origin: 'http://127.0.0.1:4184' }, data: { revision: 'stale', scene: saved } });
    assert.equal(conflict.status(), 409);
    const foreign = await page.request.put('http://127.0.0.1:4184/api/decks/lecture-2', { headers: { Origin: 'https://example.com' }, data: {} });
    assert.equal(foreign.status(), 403);
    // Manager operations persist their order in the scene, without losing data.
    await page.getByRole('button', { name: 'Add slide', exact: false }).click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li').length === n + 1, initialCount);
    await page.getByRole('button', { name: 'Move up', exact: false }).click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li')[n - 1].textContent.includes('Untitled slide'), initialCount);
    await page.locator('.undo-button-container button').click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li')[n].textContent.includes('Untitled slide'), initialCount);
    await page.locator('.redo-button-container button').click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li')[n - 1].textContent.includes('Untitled slide'), initialCount);
    await page.getByRole('button', { name: 'Renumber footers', exact: true }).click();
    await page.getByRole('button', { name: 'Save source', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Saved. A backup was kept.' }).waitFor();
    const managed = JSON.parse(await fs.readFile(path.join(fixture, 'sources/Lecture 2.excalidraw'), 'utf8'));
    const manifest = JSON.parse(await fs.readFile(path.join(fixture, 'lecture-2.json'), 'utf8'));
    assert.equal(orderedFrames(managed, manifest).length, initialCount + 1);
    assert.equal(slideEntries(managed, manifest)[initialCount - 1].title, 'Untitled slide');
    assert.ok(managed.elements.some(e => e.customData?.courseSlideNumber && e.text === String(initialCount + 1)));
    await page.reload();
    // Reloading returns to the first lecture; take its length from its manifest.
    const firstLecture = JSON.parse(await fs.readFile(path.join(fixture, 'lecture-1.json'), 'utf8')).slides.length;
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li').length === n, firstLecture);
    await page.getByLabel('Choose lecture').click();
    await page.getByRole('button', { name: 'Lecture 2: Editor fixture', exact: true }).click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li').length === n + 1, initialCount);
    await page.locator('.local-editor__slides li').nth(initialCount - 1).getByRole('button').click();
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Remove slide', exact: true }).click();
    await page.waitForFunction(n => document.querySelectorAll('.local-editor__slides li').length === n, initialCount);
    await page.getByRole('button', { name: 'Save source', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Saved. A backup was kept.' }).waitFor();
    const removed = JSON.parse(await fs.readFile(path.join(fixture, 'sources/Lecture 2.excalidraw'), 'utf8'));
    assert.ok(removed.elements.some(e => e.type === 'frame' && e.name === 'Untitled slide' && e.isDeleted));
    const libraryBefore = await fs.readFile(path.join(fixture, 'library.excalidrawlib'), 'utf8');
    const imported = { type: 'excalidrawlib', version: 2, libraryItems: [{ ...JSON.parse(libraryBefore).libraryItems[0], id: 'test-library-icon' }] };
    await page.locator('input[type=file]').last().setInputFiles({ name: 'test.excalidrawlib', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
    await page.getByRole('button', { name: 'Save library', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Library saved. A backup was kept.' }).waitFor();
    // Importing one unknown icon adds exactly one item, whatever the library holds.
    assert.equal(JSON.parse(await fs.readFile(path.join(fixture, 'library.excalidrawlib'), 'utf8')).libraryItems.length,
      JSON.parse(libraryBefore).libraryItems.length + 1);
    await page.screenshot({ path: path.join(root, 'tmp/slides-review/editor-tested.png') });
    assert.deepEqual(failures, []);
    const exported = path.join(root, 'content/slides/logic-and-ai/deck/index.json');
    const beforeStop = await fs.readFile(exported, 'utf8');
    const foreignStop = await page.request.post('http://127.0.0.1:4184/api/stop', { headers: { Origin: 'https://example.com' } });
    assert.equal(foreignStop.status(), 403);
    const exited = new Promise(resolve => child.once('exit', resolve));
    await page.getByRole('button', { name: 'Stop editor', exact: true }).click();
    await page.getByRole('heading', { name: 'Editor stopped', exact: true }).waitFor();
    assert.equal(await exited, 0);
    assert.equal(await fs.readFile(exported, 'utf8'), beforeStop);
    assert.match(output, /No rendering was run/);
  } finally { if (browser) await browser.close(); child.kill('SIGTERM'); }
});
